# Generated by Django 2.2.11 on 2020-03-10 15:37

import MonBlog.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utlisateur', djongo.models.fields.EmbeddedField(model_container=MonBlog.models.Author, null=True)),
                ('publication', djongo.models.fields.EmbeddedField(model_container=MonBlog.models.Publication, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='')),
                ('like', models.IntegerField()),
            ],
        ),
    ]
