# Generated by Django 2.2.11 on 2020-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='on_click',
            field=models.BooleanField(default=False),
        ),
    ]
