# Generated by Django 2.2.11 on 2020-03-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='on_click',
        ),
    ]
